const data = {
    products: [
      {
        name: 'Free Shirt',
        slug: 'free-shirt',
        category: 'Shirts',
        image: '/images/product-01.png',
        price: 70,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'A popular shirt',
      },
      {
        name: 'Fit Shirt',
        slug: 'fit-shir',
        category: 'Shirts',
        image: '/images/product-02.png',
        price: 80,
        brand: 'Adidas',
        rating: 4.2,
        numReviews: 10,
        countInStock: 20,
        description: 'A popular shirt',
      },
      {
        name: 'Slim Shirt',
        slug: 'slim-Shirt',
        category: 'Shirts',
        image: '/images/product-03.png',
        price: 90,
        brand: 'Raymond',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'A popular shirt',
      },
      {
        name: 'Golf Pants',
        slug: 'golf-pants',
        category: 'Pants',
        image: '/images/product-04.png',
        price: 90,
        brand: 'Oliver',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'Smart looking pants',
      },
      {
        name: 'Fit Pants',
        slug: 'fit-pants',
        category: 'Pants',
        image: '/images/product-05.png',
        price: 95,
        brand: 'Zara',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'A popular pants',
      },
      {
        name: 'Classic Pants',
        slug: 'classic-pants',
        category: 'Pants',
        image: '/images/product-06.png',
        price: 75,
        brand: 'Casely',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'A popular pants',
      },
    ],
  };
  export default data;